version: "3.4"
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64 # Apple Siliconのためplantformを指定
    environment:
      MYSQL_DATABASE: sample_development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
  db_test:
    image: mysql:8.0.33
    platform: linux/amd64 # Apple Siliconのためplantformを指定
    restart: always
    environment:
      MYSQL_DATABASE: sample_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    expose:
      - 3307
